name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'deno.json'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'deno.json'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.1

      - name: Check
        run: deno check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-read --allow-write

      - name: Get version from deno.json
        id: get_version
        run: |
          VERSION=$(deno eval "const config = JSON.parse(await Deno.readTextFile('./deno.json')); console.log(config.version);")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get previous version
        id: get_prev_version
        run: |
          PREV_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "prev_version=$PREV_VERSION" >> $GITHUB_OUTPUT

      - name: Build for Linux x86_64
        run: |
          ./tools/build.sh --arch=x86_64-unknown-linux-gnu

      - name: Build for Linux ARM64
        run: |
          ./tools/build.sh --arch=aarch64-unknown-linux-gnu

      - name: Build for macOS x86_64
        run: |
          ./tools/build.sh --arch=x86_64-apple-darwin

      - name: Build for macOS ARM64
        run: |
          ./tools/build.sh --arch=aarch64-apple-darwin

      - name: Generate changelog
        id: changelog
        run: |
          echo "## What's Changed" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          if [ "${{ steps.get_prev_version.outputs.prev_version }}" = "v0.0.0" ]; then
            git log --pretty=format:"* %s" >> CHANGELOG.md
          else
            git log ${{ steps.get_prev_version.outputs.prev_version }}..HEAD --pretty=format:"* %s" >> CHANGELOG.md
          fi
          echo "" >> CHANGELOG.md
          echo "Full Changelog: ${{ steps.get_prev_version.outputs.prev_version }}...v${{ steps.get_version.outputs.version }}" >> CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          body_path: CHANGELOG.md
          files: |
            bin/denoro-${{ steps.get_version.outputs.version }}-x86_64-unknown-linux-gnu
            bin/denoro-${{ steps.get_version.outputs.version }}-aarch64-unknown-linux-gnu
            bin/denoro-${{ steps.get_version.outputs.version }}-x86_64-apple-darwin
            bin/denoro-${{ steps.get_version.outputs.version }}-aarch64-apple-darwin
          draft: false
          prerelease: false 