name: Validate

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.1

      - name: Check
        run: deno check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-read --allow-write 